[build]
  command = "npm run build && npm run export"  # 先构建项目，再导出为静态文件
  publish = "out"                             # 指定静态文件目录

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
