backend:
  name: github
  repo:  DOCYDD/my-website
  branch: main  # ⚠️ 确保 main / master 正确

local_backend: false  # ⚠️ 添加这个可在本地测试 CMS

publish_mode: editorial_workflow  # ⚠️ 确保这一行存在
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      summary: "{{title}}"  # 在 CMS 里显示标题

backend:
  name: github
  repo: DOCYDD/my-website
  branch: main
  auth_scope: repo
