# /admin/config.yml
backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "文章"
    folder: "posts"
    create: true
    fields:
      - { name: title, label: 标题, widget: string }
      - { name: date, label: 日期, widget: datetime }
      - { name: body, label: 内容, widget: markdown }


