backend:
  name: github
  repo: DOCYDD/my-website
  branch: main  # ⚠️ 确保 main / master 正确
  auth_scope: repo  # ⚠️ 添加身份验证

local_backend: false  # ⚠️ 禁用本地模式以在 Netlify 运行

publish_mode: editorial_workflow  # ⚠️ 确保这一行存在
media_folder: "public/uploads"  # ⚠️ 修改路径以兼容不同框架
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    summary: "{{title}}"  # ⚠️ 提高 CMS 可读性
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

backend:
  name: github
  repo: DOCYDD/my-website
  branch: main
  auth_scope: repo
